void setup_devices();
void setup_termios(int fd);
int compare_strings(char *buf, char *compstr);
int write_to_logger(int fd, char *str);
int read_from_logger(int fd, char *comp_str, int flush, float timeout);
void flush(int fd);
int flash_check(int fd);
int flash_logger(int fd);
int fs_write(int fd);
int mock_factory_write(int fd, char *fct_str, char *apn);
int factory_write(int fd, char *fct_str, char *apn);
int led_test(int fd);
int measure_voltage(int fd, int i2c_fd);
int gsm_test(int fd, char *bd_str, char *ping_str, int i2c_fd, char *apn);
void inputs_config(int fd);
int generate_pulses(int fd, int i2c_fd);
int inputs_test(int fd, int i2c_fd);
int soft_rev_check(int fd, char *soft_ver);
void print_ok();
void print_fail();
void power_off(int fd);
double calculate_time(time_t *start);
void reset_logger();
void reset_nucleo(int sleeptime);
void open_fds(int *src_fd, int *dst_fd);
